services:
  postgres-db:
    # build: .
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
